import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import NextTopLoader from 'nextjs-toploader';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "arthub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark box-border">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-(--bg)`}
      >
        <NextTopLoader />
        <Toaster position="top-center" theme="dark" toastOptions={{
          style: {
            boxShadow: "0 0 50px rgba(96, 165, 250, 0.3)",
            border: "1px solid rgba(96, 165, 250, 0.3)",
            background: "#0f172a",
            color: "#fff",
          },
        }} />
        {children}
      </body>
    </html>
  );
}
